import { winColor, winDetail, winningNum, winSmallBig, colorType, winBonus } from "./elements.js";
import { period_number } from "./elements.js";
import {
    buildResultData, getLastResult,
    getColorType, getColorLabel,
    evaluateBet, calculatePayout,
    getCurrentBet, fmt
} from "./gameEngine.js";
import { isBetted, totalBetAmount } from "./events.js";

export function updateWinDialog() {
    // Result was generated by gameRecord.js/addNewRow — just read it
    const resultNum = getLastResult();
    if (resultNum === null || resultNum === undefined) return;

    const result = buildResultData(resultNum);

    // Update the drawn-result section of the dialog
    winDetail.textContent  = `Period: 30 seconds ${period_number.textContent}`;
    winSmallBig.textContent = result.isBig ? "Big" : "Small";
    winningNum.textContent  = result.randomNumber;
    winColor.textContent    = getColorLabel(result);

    // Update colour class on the result badge
    const typeRe = /^type/;
    colorType.classList.forEach(cls => { if (typeRe.test(cls)) colorType.classList.remove(cls); });
    colorType.classList.add(getColorType(result));

    // Show win/loss bonus in the dialog (only when player actually placed a bet)
    if (isBetted) {
        const bet        = getCurrentBet();
        const evaluation = evaluateBet(bet, resultNum);

        if (evaluation.won) {
            const payout = calculatePayout(totalBetAmount, evaluation.multiplier);
            winBonus.textContent = fmt(payout);
            winBonus.style.color = '#2ed573';
        } else {
            winBonus.textContent = 'You Lost';
            winBonus.style.color = '#ff4757';
        }
    }
}
